# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\hmeltz\Documents\GitHub\DesktopCalculator\UpdatingMsgBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_updating_msgbox(object):
    def setupUi(self, updating_msgbox):
        updating_msgbox.setObjectName("updating_msgbox")
        updating_msgbox.resize(214, 78)
        self.label = QtWidgets.QLabel(updating_msgbox)
        self.label.setGeometry(QtCore.QRect(10, 20, 191, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(updating_msgbox)
        QtCore.QMetaObject.connectSlotsByName(updating_msgbox)

    def retranslateUi(self, updating_msgbox):
        _translate = QtCore.QCoreApplication.translate
        updating_msgbox.setWindowTitle(_translate("updating_msgbox", "Updating"))
        self.label.setText(_translate("updating_msgbox", "Program is preparing yo install updates.\n"
"Please do not turn off your computer."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    Dlg = QtWidgets.QDialog()
    ui = Ui_updating_msgbox
    ui.setupUi(Dlg)
    
    Dlg.show()
    
    sys.exit(app.exec_())